### PR TITLE
Add test suite and refactor codebase

### LINKED ISSUE #11: Create a basic suite of tests
Refactor the code to make it more testable and write tests!

### PR DESCRIPTION
**Pull request by san650**
The idea is to refactor the code to make it more readable and organize better the code.

- [x] Create acceptance test structure
- [x] Create tests for displaying branches
- [x] Create tests for switching branches
- [x] Create tests for configuration options
- [x] Refactor how options and default configurations are processed
- [x] Refactor branch switching logic

Fixes #11

### CODE REVIEW

**Comment by san650** [comment]
@marpo60 I know we can continue refactoring the code, lot's of improvements can be made yet. But I think is enough for this PR which allows us to start working with tests on other features.

Can you review it?

cc/ @eldano

**Comment by marpo60** [comment]
@san650: sure, merge doesn't apply, Merge this branch with master :)

**Comment by san650** [comment]
@marpo60 rebase done.

**Comment by marpo60** [comment]
@san650 Looks good to me

**Pull request merged**
