### PR TITLE
Use the filesystem hierarchy standard (FHS)

### PR DESCRIPTION
**Pull request by san650**
Comply with the filesystem hierarchy standard (FHS)

http://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

```
.
├── LICENSE
├── README.md
├── bin
│   └── git-switch
├── etc
│   └── bash_completion.d
│       └── git-switch-completion.bash
├── share
│   ├── man
│   │   └── man1
│   │       └── git-switch.1
│   └── zsh
│       └── site-functions
│           └── git-switch-completion.zsh
└── test
    ├── acceptance.rb
    └── fixture.sh

9 directories, 8 files
```

### CODE REVIEW

**Comment by marpo60** [comment]
@san650 Its intended to have completion script for zsh under `share` and bash completion script under `etc`?

**Comment by san650** [comment]
I believe that under Mac OSX with brew, the `site-function` directory is on `/usr/local/share/zsh/site-functions/`, but on some Linux distros is under `/user/local/site-functions/`.

I would say that we're using mostly Mac OSX at the moment so I wouldn't be too worried about making this commit compatible with other *nix systems.

Maybe we should create a feature request to start supporting other platforms. What do you think?

**Comment by san650** [comment]
@marpo60 Do you want me to change something? Do you agree with the change of structure?

**Comment by marpo60** [comment]
Sorry for the late response.

I was asking out of curiosity only.
I agree with the change of structure.

**Pull request merged**
